import { API } from "../config/constants";

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Avaluna Commerce API",
    version: "1.1.0",
    description: "Headless services and storefront REST. Secrets never appear in examples.",
  },
  servers: [{ url: API.SERVICES_PREFIX }, { url: API.STOREFRONT_PREFIX }],
  paths: {
    "/health": { get: { summary: "Liveness and DB pings" } },
    "/openapi": { get: { summary: "This document" } },
    "/products": { get: { summary: "List catalog" }, post: { summary: "Create product" } },
    "/products/{id}": { get: { summary: "Product" }, patch: { summary: "Update" }, delete: { summary: "Delete" } },
    "/products/{id}/variations": { get: { summary: "Variations" }, post: { summary: "Add variation" } },
    "/products/{id}/images": { post: { summary: "Attach media id" } },
    "/products/{id}/relations": { get: { summary: "Related" }, post: { summary: "Relate" } },
    "/categories": { get: { summary: "Categories" }, post: { summary: "Create category" } },
    "/tags": { get: { summary: "Tags" }, post: { summary: "Create tag" } },
    "/attributes": { get: { summary: "Attributes" }, post: { summary: "Create attribute" } },
    "/attributes/{id}/terms": { post: { summary: "Attribute term" } },
    "/media": { post: { summary: "Upload image (multipart file)" } },
    "/reviews": { get: { summary: "List reviews" }, post: { summary: "Submit review (pending)" } },
    "/reviews/{id}": { patch: { summary: "Moderate pending|approved|rejected" } },
    "/orders": { get: { summary: "List orders" } },
    "/orders/{id}": { get: { summary: "Order" }, patch: { summary: "Update status" } },
    "/orders/{id}/notes": { post: { summary: "Add note" } },
    "/orders/{id}/refunds": { post: { summary: "Refund (optional restock)" } },
    "/orders/{id}/invoice": { get: { summary: "Jalali factor from order" } },
    "/orders/{id}/moadian": { post: { summary: "Submit tax invoice or 503" } },
    "/customers": { get: { summary: "Customers" }, post: { summary: "Create customer" } },
    "/promotions": { get: { summary: "Coupons" }, post: { summary: "Create coupon" } },
    "/reports/sales": { get: { summary: "Sales totals IRR" } },
    "/settings/catalog": { get: { summary: "Setting definitions" } },
    "/settings/{group}": { put: { summary: "Update setting (secrets write-only)" } },
    "/shipping-zones": { get: { summary: "Zones" } },
    "/tax-rates": { get: { summary: "VAT rates" } },
    "/payment-methods": { get: { summary: "Gateways" } },
    "/webhooks": { get: { summary: "Webhooks" }, post: { summary: "HTTPS delivery URL" } },
    "/api-keys": { get: { summary: "Service keys" }, post: { summary: "Issue key" } },
    "/locations": { get: { summary: "Warehouses" }, post: { summary: "Create location" } },
    "/inventory": { get: { summary: "Levels" }, post: { summary: "Adjust stock" } },
    "/reservations": { post: { summary: "Hold stock until TTL" } },
    "/fulfillments": { post: { summary: "Ship" }, patch: { summary: "Mark delivered" } },
    "/returns": { post: { summary: "RMA" }, patch: { summary: "Update RMA" } },
    "/labels": { post: { summary: "Buy carrier label" } },
    "/labels/{id}": { patch: { summary: "Tracking status" } },
    "/gift-cards": { post: { summary: "Issue" } },
    "/gift-cards/redeem": { post: { summary: "Redeem" } },
    "/search": { get: { summary: "Catalog search" } },
    "/abandoned-carts": { get: { summary: "Idle carts" } },
    "/loyalty": { post: { summary: "Credit points" } },
    "/notifications": { get: { summary: "Outbox list" }, post: { summary: "Queue message" } },
    "/audit": { get: { summary: "Audit log" } },
    "/payment-sessions": { post: { summary: "Start PSP" } },
    "/payment-sessions/verify": { post: { summary: "Verify PSP" } },
    "/email": { post: { summary: "Queue email" } },
    "/sms": { post: { summary: "Queue SMS" } },
    "/cron-jobs": { get: { summary: "Cron" }, post: { summary: "Register UTC cron" } },
    "/cron-jobs/tick": { post: { summary: "Run due jobs (drains outbox)" } },
    "/backups": { get: { summary: "List sqlite backups" }, post: { summary: "Copy sqlite file" } },
    "/cart": { get: { summary: "Storefront cart" } },
    "/cart/items": { post: { summary: "Add line" } },
    "/checkout": { post: { summary: "Place order" } },
    "/payments/callback": { get: { summary: "PSP return" } },
    "/auth/otp": { post: { summary: "Request OTP" } },
    "/auth/session": { post: { summary: "Verify OTP" } },
    "/account/orders": { get: { summary: "Customer orders" } },
    "/legal": { get: { summary: "Enamad / Samandehi / return days" } },
    "/seo/sitemap": { get: { summary: "XML sitemap" } },
  },
} as const;
