export const statements = [
  `CREATE TABLE IF NOT EXISTS coupons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    discount_type TEXT NOT NULL DEFAULT 'percent',
    amount INTEGER NOT NULL,
    individual_use INTEGER NOT NULL DEFAULT 0,
    usage_limit INTEGER,
    usage_limit_per_user INTEGER,
    usage_count INTEGER NOT NULL DEFAULT 0,
    free_shipping INTEGER NOT NULL DEFAULT 0,
    exclude_sale_items INTEGER NOT NULL DEFAULT 0,
    minimum_amount_cents INTEGER,
    maximum_amount_cents INTEGER,
    product_ids_json TEXT NOT NULL DEFAULT '[]',
    excluded_product_ids_json TEXT NOT NULL DEFAULT '[]',
    email_restrictions_json TEXT NOT NULL DEFAULT '[]',
    expiry_date TEXT,
    description TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS coupons_code_uq ON coupons(code);`,
  `CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    number TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    currency TEXT NOT NULL DEFAULT 'IRR',
    customer_id INTEGER,
    customer_email TEXT NOT NULL,
    billing_json TEXT NOT NULL DEFAULT '{}',
    shipping_json TEXT NOT NULL DEFAULT '{}',
    payment_method TEXT NOT NULL DEFAULT '',
    payment_method_title TEXT NOT NULL DEFAULT '',
    transaction_id TEXT,
    customer_note TEXT NOT NULL DEFAULT '',
    cart_hash TEXT,
    discount_total_cents INTEGER NOT NULL DEFAULT 0,
    shipping_total_cents INTEGER NOT NULL DEFAULT 0,
    tax_total_cents INTEGER NOT NULL DEFAULT 0,
    total_cents INTEGER NOT NULL DEFAULT 0,
    prices_include_tax INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    date_paid TEXT,
    date_completed TEXT,
    stock_taken INTEGER NOT NULL DEFAULT 0
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS orders_number_uq ON orders(number);`,
  `CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);`,
  `CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders(customer_id);`,
  `CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at);`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER,
    variation_id INTEGER,
    name TEXT NOT NULL,
    sku TEXT,
    quantity INTEGER NOT NULL,
    subtotal_cents INTEGER NOT NULL,
    total_cents INTEGER NOT NULL,
    tax_cents INTEGER NOT NULL DEFAULT 0,
    meta_json TEXT NOT NULL DEFAULT '{}'
  );`,
  `CREATE TABLE IF NOT EXISTS order_notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    note TEXT NOT NULL,
    customer_note INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS refunds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    amount_cents INTEGER NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    restock INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS carts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT NOT NULL,
    nonce TEXT NOT NULL,
    customer_id INTEGER,
    email TEXT,
    billing_json TEXT NOT NULL DEFAULT '{}',
    shipping_json TEXT NOT NULL DEFAULT '{}',
    coupons_json TEXT NOT NULL DEFAULT '[]',
    selected_shipping TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS carts_token_uq ON carts(token);`,
  `CREATE TABLE IF NOT EXISTS cart_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cart_id INTEGER NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    product_id INTEGER NOT NULL,
    variation_id INTEGER,
    quantity INTEGER NOT NULL
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS cart_items_key_uq ON cart_items(key);`,
  `CREATE TABLE IF NOT EXISTS shipping_zones (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0
  );`,
  `CREATE TABLE IF NOT EXISTS shipping_zone_locations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id INTEGER NOT NULL REFERENCES shipping_zones(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    type TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS shipping_methods (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id INTEGER NOT NULL REFERENCES shipping_zones(id) ON DELETE CASCADE,
    method_id TEXT NOT NULL,
    title TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    cost_cents INTEGER NOT NULL DEFAULT 0,
    min_amount_cents INTEGER
  );`,
  `CREATE TABLE IF NOT EXISTS tax_rates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    country TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT '',
    postcode TEXT NOT NULL DEFAULT '',
    city TEXT NOT NULL DEFAULT '',
    rate REAL NOT NULL,
    name TEXT NOT NULL,
    tax_class TEXT NOT NULL DEFAULT 'standard',
    shipping INTEGER NOT NULL DEFAULT 1,
    compound INTEGER NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 1
  );`,
  `CREATE TABLE IF NOT EXISTS payment_gateways (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 0,
    method_title TEXT NOT NULL,
    settings_json TEXT NOT NULL DEFAULT '{}'
  );`,
];
